
# tap repositories and their packages

tap homebrew/core
brew adns
brew anyenv
brew augeas
brew autoconf
brew bdw-gc
brew cairo
brew circleci
brew cloc
brew clojure
brew curl
brew dialog
brew direnv
brew fontconfig
brew fontforge
brew freetype
brew fribidi
brew gcc
brew gdbm
brew gettext
brew gh
brew ghq
brew git
brew glib
brew glide
brew gmp
brew gnu-sed
brew gnupg
brew gnutls
brew go
brew gobject-introspection
brew graphite2
brew guile
brew harfbuzz
brew hub
brew icu4c
brew isl
brew jid
brew jpeg
brew jq
brew leiningen
brew libassuan
brew libevent
brew libffi
brew libgcrypt
brew libgpg-error
brew libidn2
brew libksba
brew libmpc
brew libpng
brew libtasn1
brew libtiff
brew libtool
brew libunistring
brew libusb
brew libyaml
brew lua
brew mas
brew maven
brew mcrypt
brew memcached
brew mhash
brew mpfr
brew mysql
brew ncurses
brew nettle
brew npth
brew oniguruma
brew openapi-generator
brew openblas
brew openssl@1.1
brew p11-kit
brew pango
brew pcre
brew peco
brew perl
brew pinentry
brew pixman
brew pkg-config
brew postgresql
brew protobuf
brew python@3.8
brew r
brew readline
brew reattach-to-user-namespace
brew redis
brew rlwrap
brew ruby
brew sbt
brew scala
brew shfmt
brew sl
brew sqlite
brew tig
brew tmux
brew tree
brew unbound
brew vim
brew watch
brew watchman
brew wget
brew xz
brew zsh
brew zsh-completions

tap homebrew/cask

tap AdoptOpenJDK/openjdk
cask adoptopenjdk8

tap aws/tap
brew aws-sam-cli

tap github/gh

tap heroku/brew
brew heroku
brew heroku-node

tap k1LoW/tap
brew filt

tap kayac/tap
brew ecspresso

tap rcmdnk/file
brew brew-file

tap rcmdnk/rcmdnkpac
brew parse-plist

tap sanemat/font

tap wakeful/selection
brew yaml2json

# Other Homebrew packages
brew letsencrypt
brew openssl
brew python
brew python@2

# App Store applications
appstore 497799835 com.apple.dt.Xcode (10.2.1)
appstore 682658836 com.apple.garageband10 (10.3.2)
appstore 408981434 com.apple.iMovieApp (10.1.11)
appstore 409183694 com.apple.iWork.Keynote (9.0.1)
appstore 409203825 com.apple.iWork.Numbers (6.0)
appstore 409201541 com.apple.iWork.Pages (8.0)
appstore 823766827 com.microsoft.OneDrive-mac (19.033.0218)
appstore 425424353 cx.c3.theunarchiver (4.1.0)
